# =================================================================
# FN Media AI - Local Development Environment
# Includes Redis, Kafka, PostgreSQL, and supporting services
# =================================================================

version: '3.8'

services:
  # =================================================================
  # Main AI Service
  # =================================================================
  fn-media-ai:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fn-media-ai-dev
    ports:
      - "8000:8000"    # Main API
      - "8888:8888"    # Jupyter Lab
      - "9090:9090"    # Metrics
    volumes:
      - ./src:/home/app/src
      - ./tests:/home/app/tests
      - ./scripts:/home/app/scripts
      - ./models:/home/app/models
      - ./logs:/home/app/logs
      - ai-models-cache:/home/app/models/cache
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DATABASE_URL=postgresql://media_ai_user:media_ai_password@media-ai-postgres:5432/media_ai_db
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcs-key.json
      - OPENAI_API_KEY=${OPENAI_API_KEY:-demo-key}
      - FEATURE_GPU_ACCELERATION=false
      - AI_PROCESSING_TIMEOUT=60
    depends_on:
      - redis
      - kafka
      - media-ai-postgres
    networks:
      - findly-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # =================================================================
  # Redis - AI Result Caching
  # =================================================================
  redis:
    image: redis:7.2-alpine
    container_name: fn-media-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - findly-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # =================================================================
  # PostgreSQL - Isolated Metadata Storage for Media AI Service
  # =================================================================
  media-ai-postgres:
    image: postgres:15-alpine
    container_name: media-ai-postgres-isolated
    ports:
      - "5435:5432"  # Different port to avoid conflicts
    environment:
      POSTGRES_DB: media_ai_db
      POSTGRES_USER: media_ai_user
      POSTGRES_PASSWORD: media_ai_password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - media_ai_postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./scripts/postgres/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
    networks:
      - findly-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U media_ai_user -d media_ai_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # =================================================================
  # Apache Kafka - Event Streaming (KRaft Mode - No Zookeeper)
  # =================================================================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fn-media-ai-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft Configuration (Zookeeper-free Kafka)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - findly-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =================================================================
  # Kafka UI - Development Tool
  # =================================================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fn-media-ai-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - findly-ai-network
    restart: unless-stopped

  # =================================================================
  # MinIO - S3-compatible Storage (for testing GCS integration)
  # =================================================================
  minio:
    image: minio/minio:latest
    container_name: fn-media-ai-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - findly-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =================================================================
  # Prometheus - Metrics Collection
  # =================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: fn-media-ai-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./scripts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - findly-ai-network
    restart: unless-stopped

  # =================================================================
  # Grafana - Metrics Visualization
  # =================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: fn-media-ai-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./scripts/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./scripts/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - findly-ai-network
    restart: unless-stopped

  # =================================================================
  # Jaeger - Distributed Tracing
  # =================================================================
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fn-media-ai-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - findly-ai-network
    restart: unless-stopped

# =================================================================
# Networks
# =================================================================
networks:
  findly-ai-network:
    driver: bridge
    name: findly-ai-network

# =================================================================
# Volumes
# =================================================================
volumes:
  redis-data:
    name: fn-media-ai-redis-data
  media_ai_postgres_data:
    name: fn-media-ai-postgres-isolated-data
  kafka-data:
    name: fn-media-ai-kafka-data
  minio-data:
    name: fn-media-ai-minio-data
  prometheus-data:
    name: fn-media-ai-prometheus-data
  grafana-data:
    name: fn-media-ai-grafana-data
  ai-models-cache:
    name: fn-media-ai-models-cache